name: prim_minimum_spanning_tree
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.3

assets:
  - assets/input_edges.txt